@PMD86 /V0 /N- /K /F- /I-
@ECHO o
@ECHO == MHVN Visual Novel Engine === MHVNビジュアルノベルエンジン ==
@ECHO ==    for PC-9800 series    ===      PC-9800シリーズ用       ==
@ECHO ==     Maxim Hoxha 2023     ===    マキシム・ホジャ 2023     ==
@ECHO o
@ECHO This is a test, not a full story   : これは完全な物語じゃなくて、テストです
@ECHO Please report any bugs immediately : バグをすぐに報告してください
@ECHO o
@ECHO Starting Engine... : エンジン開始…
@MHVN98
@PMD86 /R
@ECHO Goodbye for now!