//Whole-program optimisation enabler file (doesn't include assembly files)

#include "src/platform/filehandling.c"
#include "src/platform/memalloc.c"
#include "src/platform/pc98_chargen.c"
#include "src/platform/pc98_egc.c"
#include "src/platform/pc98_grcg.c"
#include "src/platform/pc98_gdc.c"
#include "src/platform/pc98_keyboard.c"
#include "src/main.c"
#include "src/palette.c"
#include "src/stdbuffer.c"
#include "src/rootinfo.c"
#include "src/graphics.c"
#include "src/sceneengine.c"
#include "src/textengine.c"
